### ISSUE TITLE
How do you cope with dependency conflict?

### ISSUE THREAD

**Issue by pycraft114** [DriLLFreAK100/codefee-kit#25]
As I npm install, dependency conflict occurs.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: codefee-kit@0.0.29
npm ERR! Found: typescript@4.3.5
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"^4.0.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"^2.7 || ^3" from awesome-typescript-loader@5.2.1
npm ERR! node_modules/awesome-typescript-loader
npm ERR!   dev awesome-typescript-loader@"^5.2.1" from the root project

@DriLLFreAK100

**Comment by DriLLFreAK100** [comment]
Hi @pycraft114 ,

Thanks for pointing it out mate! Apparently, the package-lock.json file on my local hid the issue from me.

Anyway, I have proceed and removed 2 unused packages from the dependencies in this [commit](https://github.com/DriLLFreAK100/codefee-kit/commit/db4aa909fe5f0ac90a8d6e6d1c4a9e892b5df9e0) that was causing the conflict issue.

Please let me know if that helps :)

**Comment by pycraft114** [comment]
@DriLLFreAK100 Thx for your reply and kudos to your repository : ) 

helped me alot for building my own React components.

Have you ever tried setting a monorepo for React ? Am just asking cause I would like to ask ur opinion about some challenges while doing so.

**Comment by DriLLFreAK100** [comment]
@pycraft114 Thanks for your kind words :) Very glad that it helps! 

For monorepo, I do not have any prior experience in React settings yet. However, I am thinking of splitting this repo into multi packages by functionalities (components, hooks, utils, etc) moving forward with [Lerna ](https://github.com/lerna/lerna).

Anyway, feel free to let me know what's the issue that you are facing. Would be glad to help if I can. Perhaps, we should take this into some other communication channels :)
